# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06rag.v1\"\xcf\x01\n\x0cQueryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\r\n\x05kb_id\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\x12\r\n\x05top_k\x18\x06 \x01(\x05\x12\x17\n\x0fscore_threshold\x18\x07 \x01(\x02\x12\x1e\n\x16inference_service_name\x18\x08 \x01(\t\x12\x16\n\x0eretrieval_mode\x18\t \x01(\t\"\x86\x01\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12$\n\x07sources\x18\x02 \x03(\x0b\x32\x13.rag.v1.SourceChunk\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x14\n\x0cinput_tokens\x18\x04 \x01(\x05\x12\x15\n\routput_tokens\x18\x05 \x01(\x05\"^\n\x0bSourceChunk\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x02\x32\x41\n\tRagEngine\x12\x34\n\x05Query\x12\x14.rag.v1.QueryRequest\x1a\x15.rag.v1.QueryResponseBDZBgithub.com/kubercloud/ani/ai/rag-engine/app/generated/rag/v1;ragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/kubercloud/ani/ai/rag-engine/app/generated/rag/v1;ragv1'
  _globals['_QUERYREQUEST']._serialized_start=22
  _globals['_QUERYREQUEST']._serialized_end=229
  _globals['_QUERYRESPONSE']._serialized_start=232
  _globals['_QUERYRESPONSE']._serialized_end=366
  _globals['_SOURCECHUNK']._serialized_start=368
  _globals['_SOURCECHUNK']._serialized_end=462
  _globals['_RAGENGINE']._serialized_start=464
  _globals['_RAGENGINE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
