/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTenantsQuotasRouteImport } from './routes/_authenticated/tenants/quotas'
import { Route as AuthenticatedOpsGpuPoolRouteImport } from './routes/_authenticated/ops/gpu-pool'
import { Route as IntegrationNotificationSettingsEmailIndexRouteImport } from './routes/integration/notification-settings/email/index'
import { Route as AuthenticatedTenantsQuotasIndexRouteImport } from './routes/_authenticated/tenants/quotas/index'
import { Route as IntegrationNotificationSettingsEmailSubscriptionsRouteImport } from './routes/integration/notification-settings/email/subscriptions'
import { Route as IntegrationNotificationSettingsEmailSmtpRouteImport } from './routes/integration/notification-settings/email/smtp'
import { Route as IntegrationNotificationSettingsEmailRecipientsRouteImport } from './routes/integration/notification-settings/email/recipients'
import { Route as AuthenticatedTenantsQuotasNewRouteImport } from './routes/_authenticated/tenants/quotas.new'
import { Route as AuthenticatedTenantsQuotasPlanIdRouteImport } from './routes/_authenticated/tenants/quotas.$planId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantsQuotasRoute =
  AuthenticatedTenantsQuotasRouteImport.update({
    id: '/tenants/quotas',
    path: '/tenants/quotas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsGpuPoolRoute = AuthenticatedOpsGpuPoolRouteImport.update({
  id: '/ops/gpu-pool',
  path: '/ops/gpu-pool',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const IntegrationNotificationSettingsEmailIndexRoute =
  IntegrationNotificationSettingsEmailIndexRouteImport.update({
    id: '/integration/notification-settings/email/',
    path: '/integration/notification-settings/email/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTenantsQuotasIndexRoute =
  AuthenticatedTenantsQuotasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantsQuotasRoute,
  } as any)
const IntegrationNotificationSettingsEmailSubscriptionsRoute =
  IntegrationNotificationSettingsEmailSubscriptionsRouteImport.update({
    id: '/integration/notification-settings/email/subscriptions',
    path: '/integration/notification-settings/email/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationNotificationSettingsEmailSmtpRoute =
  IntegrationNotificationSettingsEmailSmtpRouteImport.update({
    id: '/integration/notification-settings/email/smtp',
    path: '/integration/notification-settings/email/smtp',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationNotificationSettingsEmailRecipientsRoute =
  IntegrationNotificationSettingsEmailRecipientsRouteImport.update({
    id: '/integration/notification-settings/email/recipients',
    path: '/integration/notification-settings/email/recipients',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTenantsQuotasNewRoute =
  AuthenticatedTenantsQuotasNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTenantsQuotasRoute,
  } as any)
const AuthenticatedTenantsQuotasPlanIdRoute =
  AuthenticatedTenantsQuotasPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedTenantsQuotasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ops/gpu-pool': typeof AuthenticatedOpsGpuPoolRoute
  '/tenants/quotas': typeof AuthenticatedTenantsQuotasRouteWithChildren
  '/tenants/quotas/$planId': typeof AuthenticatedTenantsQuotasPlanIdRoute
  '/tenants/quotas/new': typeof AuthenticatedTenantsQuotasNewRoute
  '/integration/notification-settings/email/recipients': typeof IntegrationNotificationSettingsEmailRecipientsRoute
  '/integration/notification-settings/email/smtp': typeof IntegrationNotificationSettingsEmailSmtpRoute
  '/integration/notification-settings/email/subscriptions': typeof IntegrationNotificationSettingsEmailSubscriptionsRoute
  '/tenants/quotas/': typeof AuthenticatedTenantsQuotasIndexRoute
  '/integration/notification-settings/email/': typeof IntegrationNotificationSettingsEmailIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/ops/gpu-pool': typeof AuthenticatedOpsGpuPoolRoute
  '/tenants/quotas/$planId': typeof AuthenticatedTenantsQuotasPlanIdRoute
  '/tenants/quotas/new': typeof AuthenticatedTenantsQuotasNewRoute
  '/integration/notification-settings/email/recipients': typeof IntegrationNotificationSettingsEmailRecipientsRoute
  '/integration/notification-settings/email/smtp': typeof IntegrationNotificationSettingsEmailSmtpRoute
  '/integration/notification-settings/email/subscriptions': typeof IntegrationNotificationSettingsEmailSubscriptionsRoute
  '/tenants/quotas': typeof AuthenticatedTenantsQuotasIndexRoute
  '/integration/notification-settings/email': typeof IntegrationNotificationSettingsEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ops/gpu-pool': typeof AuthenticatedOpsGpuPoolRoute
  '/_authenticated/tenants/quotas': typeof AuthenticatedTenantsQuotasRouteWithChildren
  '/_authenticated/tenants/quotas/$planId': typeof AuthenticatedTenantsQuotasPlanIdRoute
  '/_authenticated/tenants/quotas/new': typeof AuthenticatedTenantsQuotasNewRoute
  '/integration/notification-settings/email/recipients': typeof IntegrationNotificationSettingsEmailRecipientsRoute
  '/integration/notification-settings/email/smtp': typeof IntegrationNotificationSettingsEmailSmtpRoute
  '/integration/notification-settings/email/subscriptions': typeof IntegrationNotificationSettingsEmailSubscriptionsRoute
  '/_authenticated/tenants/quotas/': typeof AuthenticatedTenantsQuotasIndexRoute
  '/integration/notification-settings/email/': typeof IntegrationNotificationSettingsEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/ops/gpu-pool'
    | '/tenants/quotas'
    | '/tenants/quotas/$planId'
    | '/tenants/quotas/new'
    | '/integration/notification-settings/email/recipients'
    | '/integration/notification-settings/email/smtp'
    | '/integration/notification-settings/email/subscriptions'
    | '/tenants/quotas/'
    | '/integration/notification-settings/email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/auth/callback'
    | '/'
    | '/ops/gpu-pool'
    | '/tenants/quotas/$planId'
    | '/tenants/quotas/new'
    | '/integration/notification-settings/email/recipients'
    | '/integration/notification-settings/email/smtp'
    | '/integration/notification-settings/email/subscriptions'
    | '/tenants/quotas'
    | '/integration/notification-settings/email'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/ops/gpu-pool'
    | '/_authenticated/tenants/quotas'
    | '/_authenticated/tenants/quotas/$planId'
    | '/_authenticated/tenants/quotas/new'
    | '/integration/notification-settings/email/recipients'
    | '/integration/notification-settings/email/smtp'
    | '/integration/notification-settings/email/subscriptions'
    | '/_authenticated/tenants/quotas/'
    | '/integration/notification-settings/email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  IntegrationNotificationSettingsEmailRecipientsRoute: typeof IntegrationNotificationSettingsEmailRecipientsRoute
  IntegrationNotificationSettingsEmailSmtpRoute: typeof IntegrationNotificationSettingsEmailSmtpRoute
  IntegrationNotificationSettingsEmailSubscriptionsRoute: typeof IntegrationNotificationSettingsEmailSubscriptionsRoute
  IntegrationNotificationSettingsEmailIndexRoute: typeof IntegrationNotificationSettingsEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants/quotas': {
      id: '/_authenticated/tenants/quotas'
      path: '/tenants/quotas'
      fullPath: '/tenants/quotas'
      preLoaderRoute: typeof AuthenticatedTenantsQuotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/gpu-pool': {
      id: '/_authenticated/ops/gpu-pool'
      path: '/ops/gpu-pool'
      fullPath: '/ops/gpu-pool'
      preLoaderRoute: typeof AuthenticatedOpsGpuPoolRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/integration/notification-settings/email/': {
      id: '/integration/notification-settings/email/'
      path: '/integration/notification-settings/email'
      fullPath: '/integration/notification-settings/email/'
      preLoaderRoute: typeof IntegrationNotificationSettingsEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants/quotas/': {
      id: '/_authenticated/tenants/quotas/'
      path: '/'
      fullPath: '/tenants/quotas/'
      preLoaderRoute: typeof AuthenticatedTenantsQuotasIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsQuotasRoute
    }
    '/integration/notification-settings/email/subscriptions': {
      id: '/integration/notification-settings/email/subscriptions'
      path: '/integration/notification-settings/email/subscriptions'
      fullPath: '/integration/notification-settings/email/subscriptions'
      preLoaderRoute: typeof IntegrationNotificationSettingsEmailSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/notification-settings/email/smtp': {
      id: '/integration/notification-settings/email/smtp'
      path: '/integration/notification-settings/email/smtp'
      fullPath: '/integration/notification-settings/email/smtp'
      preLoaderRoute: typeof IntegrationNotificationSettingsEmailSmtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/notification-settings/email/recipients': {
      id: '/integration/notification-settings/email/recipients'
      path: '/integration/notification-settings/email/recipients'
      fullPath: '/integration/notification-settings/email/recipients'
      preLoaderRoute: typeof IntegrationNotificationSettingsEmailRecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants/quotas/new': {
      id: '/_authenticated/tenants/quotas/new'
      path: '/new'
      fullPath: '/tenants/quotas/new'
      preLoaderRoute: typeof AuthenticatedTenantsQuotasNewRouteImport
      parentRoute: typeof AuthenticatedTenantsQuotasRoute
    }
    '/_authenticated/tenants/quotas/$planId': {
      id: '/_authenticated/tenants/quotas/$planId'
      path: '/$planId'
      fullPath: '/tenants/quotas/$planId'
      preLoaderRoute: typeof AuthenticatedTenantsQuotasPlanIdRouteImport
      parentRoute: typeof AuthenticatedTenantsQuotasRoute
    }
  }
}

interface AuthenticatedTenantsQuotasRouteChildren {
  AuthenticatedTenantsQuotasPlanIdRoute: typeof AuthenticatedTenantsQuotasPlanIdRoute
  AuthenticatedTenantsQuotasNewRoute: typeof AuthenticatedTenantsQuotasNewRoute
  AuthenticatedTenantsQuotasIndexRoute: typeof AuthenticatedTenantsQuotasIndexRoute
}

const AuthenticatedTenantsQuotasRouteChildren: AuthenticatedTenantsQuotasRouteChildren =
  {
    AuthenticatedTenantsQuotasPlanIdRoute:
      AuthenticatedTenantsQuotasPlanIdRoute,
    AuthenticatedTenantsQuotasNewRoute: AuthenticatedTenantsQuotasNewRoute,
    AuthenticatedTenantsQuotasIndexRoute: AuthenticatedTenantsQuotasIndexRoute,
  }

const AuthenticatedTenantsQuotasRouteWithChildren =
  AuthenticatedTenantsQuotasRoute._addFileChildren(
    AuthenticatedTenantsQuotasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOpsGpuPoolRoute: typeof AuthenticatedOpsGpuPoolRoute
  AuthenticatedTenantsQuotasRoute: typeof AuthenticatedTenantsQuotasRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOpsGpuPoolRoute: AuthenticatedOpsGpuPoolRoute,
  AuthenticatedTenantsQuotasRoute: AuthenticatedTenantsQuotasRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  IntegrationNotificationSettingsEmailRecipientsRoute:
    IntegrationNotificationSettingsEmailRecipientsRoute,
  IntegrationNotificationSettingsEmailSmtpRoute:
    IntegrationNotificationSettingsEmailSmtpRoute,
  IntegrationNotificationSettingsEmailSubscriptionsRoute:
    IntegrationNotificationSettingsEmailSubscriptionsRoute,
  IntegrationNotificationSettingsEmailIndexRoute:
    IntegrationNotificationSettingsEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
